# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .exec_ import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "postgresql-exec",
  "mod": "index",
  "fqn": "pulumi_postgresql_exec",
  "classes": {
   "postgresql-exec:index:Exec": "Exec"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "postgresql-exec",
  "token": "pulumi:providers:postgresql-exec",
  "fqn": "pulumi_postgresql_exec",
  "class": "Provider"
 }
]
"""
)
